### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by cuducos** [flask-extensions/Flask-SimpleLogin#19]
Maybe it's just me (and my dear OCD), but what are the odds we might break something by renaming this repo `Flask-SimpleLogin`?
 
![image](https://user-images.githubusercontent.com/4732915/69092650-dbb94100-0a1a-11ea-9df3-5d7bb1c4d0ee.png)

We might to update the documentation, update the Travis's URLs in the `README.md`  and that's all, right?

cc @Riverfount and, maybe, @rochacbruno

**Comment by Riverfount** [comment]
@cuducos I think that may be dangerous. It all depends on the use of this extension. If many projects use this extension we have great chances to break them! No?

**Comment by rochacbruno** [comment]
I guess github creates redirects when a repo is renamed, so the old name will still be accessible.

**Comment by cuducos** [comment]
@Riverfount, I'm afraid changing the repository name in GitHub doesn't affect the name on PyPI or in the extension namespace, right?

@rochacbruno, yes, redirect is done automagically by GitHub, I believe.
