### ISSUE TITLE
csrf_token The CSRF token is invalid

### ISSUE THREAD

**Issue by gd03champ** [flask-extensions/Flask-SimpleLogin#32]
I've hosted flask in heroku. When I login through desktop it's working but when I login through mobile, I get this error.

![Screenshot_20220821-163718_Brave.jpg](https://user-images.githubusercontent.com/63779654/185788150-c9303479-b605-42eb-a993-056abcb830f4.jpg)

After attempting once in mobile, the error continues in desktop too until I deploy fresh.
 
what could have gone wrong?

**Comment by cuducos** [comment]
> what could have gone wrong?

Is it a custom form?

* If so, you might have forgotten the CSRF token (in [the docs example](https://flask-simple-login.readthedocs.io/en/latest/customizing.html), the line `{{ form.csrf_token }}`), or it might be outside the form.
* If not, can you share your source code or an example project to reproduce the error?

**Comment by gd03champ** [comment]
Thanks for replying.
The error resolved after setting secret key rather letting it create it's own on random.  ✌️
